apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
  name: kubernation
  labels:
    app: kubernation
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: kubernation-dashboard
          servicePort: 8080
      - path: /api
        backend:
          serviceName: kubernation-api
          servicePort: 8080
  tls:
    - hosts:
      - {{ .Values.domain }}
      secretName: kubernation-tls
