apiVersion: v1
kind: Service
metadata:
  name: kubernation-api
  labels:
    app: kubernation-api
    chart: kubernation
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kubernation-api
---
apiVersion: v1
kind: Service
metadata:
  name: kubernation-dashboard
  labels:
    app: kubernation-dashboard
    chart: kubernation
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kubernation-dashboard
